#!/usr/bin/env python3
"""Generate config/wnl_pathways/part_catalog.json with richer hints + short/tall/wide size
variants for every modular part that benefits from them. Whole-structure + tiny-deco parts
stay single-size. Run with the game CLOSED; the mod uses this file as-is (won't overwrite)."""
import json, os

# base parts: (category, name, w, d, h, hint, axes)
#   axes = which size variants to also emit:  s=short(lower)  t=tall(higher)  w=wide(longer)
BASE = [
  ("masonry","wall",          6,2,8, "main wall tile — tiles sideways; vary stone bricks/cracked/mossy ~15% for age","stw"),
  ("masonry","wall_corner",   6,6,8, "outside corner — wrap the bond, add a quoin/pilaster on the angle","t"),
  ("masonry","buttress",      3,4,12,"wall pier — projects from the face, steps back as it rises","st"),
  ("masonry","arcade",        12,2,8,"a run of repeating arches (cloister/aqueduct); keep piers even","tw"),
  ("masonry","arch",          6,2,7, "single arched opening — voussoirs + a keystone at the crown","stw"),
  ("masonry","pillar",        3,3,12,"free column — base + shaft + capital; entasis looks natural","st"),
  ("masonry","plinth",        6,2,3, "base course the wall sits on — wider than the wall above","w"),
  ("masonry","string_course", 6,2,1, "belt line across the facade — a slab/stair ledge breaks flat walls","w"),
  ("masonry","corbel",        6,2,2, "projecting bracket course carrying the storey above","w"),
  ("battlement","battlement",     6,2,3, "merlon/crenel top — 2-high wall, 1-gap, alternating","tw"),
  ("battlement","parapet_walk",   8,4,4, "walkable wall-top: floor + inner rail + outer crenels","tw"),
  ("battlement","arrow_loop",     2,2,5, "arrow slit — narrow outside, splayed wide inside","st"),
  ("battlement","machicolation",  6,3,4, "overhang gallery with drop-holes between corbels","w"),
  ("opening","window",        2,2,4, "small window — frame it, add a sill + a hint of depth","stw"),
  ("opening","window_arched", 4,2,8, "arched/traceried window — mullions + glass set back","tw"),
  ("opening","doorway",       4,3,7, "door opening — surround + lintel/arch, recessed reveal","tw"),
  ("opening","portcullis",    7,2,9, "raised iron grille in a gate slot","tw"),
  ("opening","gate_arch",     13,4,13,"carriageway frontispiece — the main entry, make it monumental","tw"),
  ("tower","tower_base",      13,13,6, "battered (sloped) tower foot — wider than the shaft","w"),
  ("tower","tower_storey",    9,9,7,   "one tower floor — stack these; windows climb each storey","tw"),
  ("tower","tower_roof",      13,13,11,"tower cap — conical/pyramidal roof + a walkable ring below","w"),
  ("tower","turret",          7,7,12,  "slim corner turret — caps a wall junction","st"),
  ("roof","roof_gable",       9,7,7,  "two-slope gable — steeper reads more medieval","tw"),
  ("roof","roof_hip",         9,9,7,  "four-slope hip roof — good on square towers/halls","w"),
  ("roof","spire",            7,7,14, "tall steeple — octagonal base into a needle","st"),
  ("roof","dormer",           3,3,4,  "roof window box poking through a slope","w"),
  ("roof","chimney",          2,2,9,  "chimney stack — corbel the top, vary the brick","st"),
  ("bridge","bridge_pier",    3,3,10, "bridge support — cutwater (pointed nose) faces upstream","st"),
  ("bridge","bridge_span",    8,4,3,  "deck tile — repeat between piers","w"),
  ("bridge","bridge_railing", 8,1,3,  "parapet/railing edge for the deck","w"),
  ("bridge","bridge_arch",    9,3,7,  "arch ring under the deck between piers","tw"),
  ("shrine","shrine_column",  3,3,10, "temple column — fluting + a clear capital","st"),
  ("shrine","pediment",       9,3,5,  "triangular gable over a colonnade","w"),
  ("shrine","altar",          3,2,3,  "altar/shrine focus block — raise it on steps","w"),
  ("shrine","statue",         3,3,7,  "figure on a plinth — silhouette matters most","st"),
  ("well","well_head",        3,3,3,  "well kerb + windlass posts","w"),
  ("well","well_roof",        5,5,4,  "little canopy roof over the well","w"),
  ("marker","cairn_tier",     5,5,3,  "stacked-stone tier — taper as it rises","w"),
  ("marker","cairn_cap",      3,3,4,  "cairn capstone / finial","t"),
  ("marker","milestone",      2,2,4,  "roadside distance marker","t"),
  ("marker","waystone",       3,3,5,  "standing menhir / waymarker","t"),
  ("wayside","lamp_post",     2,2,7,  "lantern post — reads day AND night without the light","st"),
  ("wayside","bench",         3,2,2,  "rest bench","w"),
  ("wayside","firepit",       3,3,2,  "rest-stop firepit + seating ring","w"),
  ("wayside","market_stall",  5,5,6,  "market stall with awning + goods","w"),
  ("garden","fountain",       5,5,4,  "fountain — water source + tiers","w"),
  ("garden","planter",        3,3,2,  "raised planter box","w"),
  ("garden","trough",         4,2,2,  "water/feed trough","w"),
  ("ruins","ruin_wall",       7,3,6,  "broken wall — jagged top, missing blocks, vines","tw"),
  ("ruins","rubble_pile",     5,5,3,  "collapsed rubble heap — mixed stone + dirt","w"),
  ("ruins","broken_column",   2,2,6,  "snapped/toppled column + drum sections","st"),
  # walls WITH openings — pre-composed sections (the parts you actually paste into a facade)
  ("openwall","wall_window",      8,2,8, "wall section with one window — frame + sill + recessed reveal","stw"),
  ("openwall","wall_window_dbl",  12,2,8,"wall with a pair of evenly-spaced windows","tw"),
  ("openwall","wall_window_arch", 8,2,10,"wall with an arched/traceried window","tw"),
  ("openwall","wall_door",        8,2,8, "wall with a doorway + surround/lintel","tw"),
  ("openwall","wall_gate",        13,3,12,"wall with a gate passage + flanking piers","t"),
  ("openwall","wall_arrowloops",  8,2,9, "defensive wall run pierced with arrow slits","tw"),
  ("openwall","wall_oriel",       8,3,10,"wall with a projecting oriel/bay window upstairs","tw"),
  ("openwall","wall_shopfront",   8,2,7, "ground-floor shopfront opening + counter","tw"),
  # fine detail / ornament — the touches that lift a build
  ("detail","gargoyle",       2,3,2, "projecting waterspout grotesque on a corbel","s"),
  ("detail","finial",         2,2,4, "rooftop / gable-tip ornament","t"),
  ("detail","crocket",        2,2,2, "leafy hook climbing a spire edge",""),
  ("detail","weathervane",    1,2,4, "spire-top vane","t"),
  ("detail","heraldry",       3,1,3, "wall crest / coat-of-arms panel","w"),
  ("detail","keystone_boss",  2,2,2, "carved boss for an arch crown / vault",""),
  ("detail","sundial",        3,3,3, "pedestal sundial",""),
  ("detail","quoin",          2,2,6, "dressed corner stones (alternating long/short)","t"),
  # interior fittings
  ("interior","fireplace",     4,2,5, "hearth + mantel + flue into a chimney","tw"),
  ("interior","spiral_stair",  5,5,11,"tower spiral staircase — newel + winders","t"),
  ("interior","straight_stair",3,6,5, "straight flight + landing","tw"),
  ("interior","rose_window",   7,2,7, "circular traceried window","w"),
  ("interior","groin_vault",   7,7,5, "intersecting vault bay (ceiling)","w"),
  ("interior","colonnade_bay", 6,4,9, "interior column bay (nave / cloister)","tw"),
  ("interior","gallery",       9,3,4, "upstairs gallery / minstrels' loft","w"),
  # defensive features
  ("defense","hoarding",       8,3,4, "timber wall-top fighting gallery (overhangs)","tw"),
  ("defense","drawbridge",     7,6,3, "gate drawbridge + chains","w"),
  ("defense","barbican",       13,9,12,"forward gate-defence work","tw"),
  ("defense","murder_hole",    4,4,3, "gate-passage drop trap (holes overhead)",""),
  ("defense","battered_plinth",8,3,4, "sloped (battered) base course for strength","w"),
  # civic / settlement props
  ("civic","market_cross",     5,5,9, "stepped market cross — town centrepiece","t"),
  ("civic","dovecote",         5,5,10,"round/square pigeon house","t"),
  ("civic","bake_oven",        4,4,4, "communal domed bread oven",""),
  ("civic","forge",            5,4,5, "smithy forge + chimney + anvil","w"),
  ("civic","stocks",           3,2,3, "village stocks / pillory",""),
  ("civic","notice_board",     3,2,4, "town notice / wayfinding board","w"),
  # more roofs
  ("roof","roof_mansard",  9,9,8, "double-pitch mansard (steep lower slope)","w"),
  ("roof","roof_gambrel",  9,7,7, "barn-style gambrel roof","w"),
  ("roof","roof_conical",  9,9,10,"round conical tower cap","t"),
  ("roof","roof_thatch",   9,7,6, "steep thatch with an organic edge","w"),
  ("roof","roof_leanto",   6,4,4, "single-slope lean-to / pentice","w"),
  ("roof","cupola",        5,5,7, "rooftop lantern / cupola","t"),
  ("roof","belfry",        7,7,9, "open bell stage","t"),
  # more windows / openings
  ("opening","lancet",     2,2,7, "tall narrow pointed window","t"),
  ("opening","oculus",     3,2,3, "round eye window","w"),
  ("opening","clerestory", 10,2,4,"high row of small windows","w"),
  ("opening","bay_window", 5,3,7, "projecting bay window","tw"),
  ("opening","cross_loop", 2,2,5, "cross-shaped arrow/gun loop","t"),
  # tower shapes
  ("tower","tower_round",  11,11,8,"round drum tower storey","t"),
  ("tower","tower_octagon",11,11,8,"octagonal tower storey","t"),
  ("tower","tower_dshape", 11,9,8, "D-shaped (flat-back) wall tower","t"),
  ("tower","gate_tower",   9,9,14, "twin-tower gate flanker","t"),
  # Roman / classical
  ("roman","aqueduct_arch", 9,3,12, "aqueduct arch bay — repeat for a span","tw"),
  ("roman","triumphal_arch",13,5,13,"monumental single/triple arch","tw"),
  ("roman","colonnade",     12,3,9, "row of classical columns + entablature","tw"),
  ("roman","temple_front",  13,7,13,"portico — columns under a pediment","tw"),
  ("roman","victory_column",4,4,16, "commemorative column + statue","t"),
  ("roman","amphitheatre_tier",13,5,5,"raked seating tier","w"),
  ("roman","rostra",        7,4,4,  "speaker's platform","w"),
  ("roman","atrium",        13,13,7,"courtyard with an impluvium pool","w"),
  ("roman","arcade_orders", 8,4,12, "tiered arcaded facade (stacked orders)","t"),
  # medieval timber
  ("timber","tudor_wall",   8,2,8, "timber-frame infill wall (wattle/daub)","stw"),
  ("timber","jetty",        8,3,3, "overhanging jettied upper storey","w"),
  ("timber","timber_gable", 7,3,7, "half-timbered gable end","tw"),
  ("timber","cruck_frame",  7,5,8, "curved cruck-beam frame bay","t"),
  ("timber","undercroft",   9,9,5, "vaulted stone cellar under timber","w"),
  ("timber","inn_gallery",  11,4,9,"galleried inn courtyard range","tw"),
  # religious
  ("religious","apse",          9,7,9,  "semicircular sanctuary end","t"),
  ("religious","transept",      9,7,12, "cross-arm of a church","tw"),
  ("religious","flying_buttress",4,8,12,"arched external buttress","t"),
  ("religious","bell_cote",     3,2,5,  "small wall bell-housing","t"),
  ("religious","lych_gate",     5,4,5,  "covered churchyard gate","w"),
  ("religious","cloister_walk", 10,4,5, "covered arcaded walkway","w"),
  ("religious","baptistry",     9,9,11, "octagonal font building","t"),
  ("religious","crypt_vault",   9,9,4,  "low vaulted crypt bay","w"),
  ("religious","wayside_cross", 3,3,6,  "roadside cross / shrine","t"),
  # trade / industry
  ("trade","guildhall_front",13,3,12,"grand guild / town-hall facade","t"),
  ("trade","tithe_barn",     15,11,12,"great aisled barn","tw"),
  ("trade","granary",        7,7,9,  "raised staddle-stone granary","t"),
  ("trade","watermill",      11,9,10,"mill house + waterwheel","tw"),
  ("trade","windmill",       9,9,16, "tower windmill + sails","t"),
  ("trade","warehouse",      13,9,10,"dockside warehouse + hoist","tw"),
  ("trade","dock_crane",     5,5,11, "timber wharf crane","t"),
  ("trade","kiln",           5,5,7,  "pottery / lime kiln","t"),
  # props / clutter (life between the buildings)
  ("props","cart",        5,2,3, "wooden cart","w"),
  ("props","haystack",    3,3,4, "hay stack","w"),
  ("props","crates",      3,3,3, "stacked crates + barrels","w"),
  ("props","signpost",    2,3,5, "wayfinding signpost","t"),
  ("props","gibbet",      3,3,6, "roadside gibbet / gallows","t"),
  ("props","woodpile",    4,2,3, "stacked firewood","w"),
  # ===================== BRIDGES — the ridiculous kit =====================
  # bridge = components · bridge_span = whole spans/types · bridge_build = stuff ON the bridge
  ("bridge","pier_cutwater",    4,5,11,"pier with a pointed cutwater (splits the current)","st"),
  ("bridge","pier_round",       4,4,11,"round drum river pier","st"),
  ("bridge","pier_square",      4,4,11,"square ashlar pier","st"),
  ("bridge","pier_battered",    5,5,11,"battered (sloped) pier base","s"),
  ("bridge","starling",         6,6,3, "timber starling / ice-breaker ring round a pier","w"),
  ("bridge","abutment",         7,5,8, "bank end — where the bridge meets land","tw"),
  ("bridge","pile_bent",        5,3,9, "group of timber piles (trestle leg)","st"),
  ("bridge","springer",         4,3,4, "arch springing stone off the pier",""),
  ("bridge","arch_semicircular",9,3,7, "Roman semicircular arch ring","tw"),
  ("bridge","arch_segmental",   10,3,5,"flatter segmental arch ring","w"),
  ("bridge","arch_pointed",     8,3,9, "gothic pointed arch ring","tw"),
  ("bridge","arch_ogee",        8,3,8, "S-curved ogee arch ring","t"),
  ("bridge","spandrel",         9,3,4, "wall face above/between arches","w"),
  ("bridge","keystone",         2,3,3, "carved keystone for the arch crown",""),
  ("bridge","deck_narrow",      6,3,2, "narrow roadway tile (1 cart)","w"),
  ("bridge","deck_wide",        9,5,2, "wide roadway tile (2 cart + walkways)","w"),
  ("bridge","deck_cobbled",     8,4,2, "cobbled deck with a drainage camber","w"),
  ("bridge","parapet_stone",    8,1,4, "solid stone parapet","tw"),
  ("bridge","balustrade",       8,1,3, "turned-baluster railing","w"),
  ("bridge","parapet_crenel",   8,1,4, "crenellated (defensive) parapet","w"),
  ("bridge","railing_iron",     8,1,3, "wrought-iron railing","w"),
  ("bridge","railing_wood",     8,1,3, "timber post-and-rail","w"),
  ("bridge","refuge_bay",       4,4,5, "pedestrian refuge pocket over a pier","t"),
  ("bridge","bridge_lamp",      2,2,7, "deck lamp post","t"),
  ("bridge","bollard",          2,2,3, "mooring / edge bollard",""),
  ("bridge","drain_spout",      3,2,2, "deck drainage gargoyle spout",""),
  ("bridge","ramp_approach",    9,4,4, "graded ramp up to the deck","tw"),
  ("bridge","stair_approach",   4,6,5, "stepped approach to the deck","tw"),
  ("bridge_span","stone_arch",     13,5,12,"one stone arch + deck — the classic span","tw"),
  ("bridge_span","viaduct_bay",    11,4,16,"tall repeatable arched viaduct bay","tw"),
  ("bridge_span","beam_timber",    10,4,6, "simple timber beam span","w"),
  ("bridge_span","trestle",        10,5,12,"wooden X-frame trestle span","tw"),
  ("bridge_span","covered",        11,7,9, "roofed (covered) bridge span","tw"),
  ("bridge_span","packhorse_hump", 9,4,8,  "narrow humpbacked packhorse span","w"),
  ("bridge_span","clapper",        9,4,4,  "flat stone slabs on low piers","w"),
  ("bridge_span","suspension_tower",6,6,18,"suspension pylon / tower","t"),
  ("bridge_span","suspension_deck",13,4,4, "cable-hung suspension deck section","w"),
  ("bridge_span","rope",           9,3,5,  "simple rope-and-plank span","w"),
  ("bridge_span","drawbridge",     8,6,4,  "lifting drawbridge leaf + chains","w"),
  ("bridge_span","bascule",        9,7,5,  "counterweighted bascule span","w"),
  ("bridge_span","pontoon",        11,5,3, "floating pontoon section","w"),
  ("bridge_span","causeway",       11,3,4, "low stone causeway embankment","w"),
  ("bridge_span","cantilever",     13,4,8, "cantilever arm span","tw"),
  ("bridge_span","truss",          12,4,7, "trussed (framed) span","tw"),
  ("bridge_span","aqueduct",       9,4,12, "water-channel aqueduct span","tw"),
  ("bridge_build","bridge_chapel",   7,6,11,"chapel built onto the bridge","t"),
  ("bridge_build","bridge_gatehouse",9,8,15,"fortified gate tower on the bridge","t"),
  ("bridge_build","bridge_shops",    13,5,9,"shops/houses overhanging the deck (Ponte Vecchio)","tw"),
  ("bridge_build","toll_house",      6,5,7, "toll / keeper's house + barrier","tw"),
  ("bridge_build","bridgehead",      11,9,12,"fortified bridge-end work","tw"),
  # ===================== SPEC §4.2 — waterfront: piers, harbours, docks =====================
  ("waterfront","fisher_jetty",   10,3,4, "small wooden jetty on piles — fisher loot","tw"),
  ("waterfront","stone_jetty",    12,4,4, "low stone jetty out over the water","tw"),
  ("waterfront","ruined_pier",    10,3,4, "broken weathered jetty (dead-end terminus)","w"),
  ("waterfront","dock_shack",     7,6,7,  "tiny fisher shack — barrels/net/lantern (enterable, door 2x3)","tw"),
  ("waterfront","stone_quay",     16,8,6, "large stone quay + dark-prismarine waterline","tw"),
  ("waterfront","timber_wharf",   16,8,6, "timber wharf decking + bollards","tw"),
  ("waterfront","ruined_harbour", 16,8,6, "collapsed half-sunk quay (wild terminus)","w"),
  ("waterfront","quay_crane",     5,5,12, "harbour cargo crane (timber/iron)","t"),
  ("waterfront","mooring_capstan",3,3,3,  "capstan + mooring posts",""),
  ("waterfront","breakwater",     13,4,4, "stone sea-wall / breakwater","w"),
  ("waterfront","lighthouse",     9,9,22, "harbour lighthouse / pharos (sea-lantern crown)","t"),
  ("waterfront","slipway",        6,5,4,  "boat ramp down to the water","w"),
  ("waterfront","net_rack",       4,2,4,  "net-drying rack + floats","w"),
  ("waterfront","fish_market",    9,7,6,  "open-air fish-market stalls","tw"),
  ("waterfront","boathouse",      11,8,8, "covered boathouse (enterable)","tw"),
  # ===================== SPEC §5 — waymarkers, shrines, hubs (the wnl_* deco pieces) =====================
  ("waymark","wayshrine",     5,4,7,  "mossy roadside shrine, candle/lantern (R1 niche -> R5 pillared arch)","tw"),
  ("waymark","wayshrine_ruin",6,4,5,  "collapsed wayshrine — the ruin-terminus marker (lootable)","w"),
  ("waymark","menhir",        3,3,9,  "single leaning standing-stone monolith (wild, unlit, primal)","st"),
  ("waymark","obelisk",       7,7,20, "tapering chiselled civic column — viaduct/harbour entrance","t"),
  ("waymark","banner_stand",  4,2,6,  "twin posts + banner pair on a stone base","w"),
  ("waymark","cairn_tribute", 5,5,8,  "special hand-stacked cairn + plaque (Cairn co-creator tribute)","t"),
  ("waymark","plaza",         17,17,3,"open paved gathering plaza (Roman-forum-inspired)","w"),
  ("waymark","fountain_plaza",9,9,5,  "plaza centrepiece fountain","w"),
  ("waymark","rest_stop",     9,9,4,  "wayside camp: campfire + barrels + stumps + lantern post","w"),
  ("waymark","lean_to",       6,4,5,  "open-front shelter / lean-to","w"),
  ("waymark","camp_furnished",11,9,5, "great-road furnished camp (lean-to + lanterns + banner)","w"),
  ("waymark","toll_gate",     11,5,11,"road toll arch-gate (opening >= road width, scales w/ tier)","tw"),
  ("waymark","credit_sign",   2,2,4,  "rare easter-egg sign (credits Moog's Paths / FinnDog)",""),
  # ===================== CREATIVE MEDIEVAL EXPANSION =====================
  # --- village life ---
  ("village","pigsty",        5,4,3, "mud pig pen + lean-to shelter","w"),
  ("village","chicken_coop",  4,3,4, "hen house on legs + run","w"),
  ("village","beehive",       3,3,4, "straw skeps on a stand","w"),
  ("village","rabbit_hutch",  3,2,3, "raised rabbit hutch",""),
  ("village","dog_kennel",    3,3,3, "kennel + chained post",""),
  ("village","village_pump",  2,2,4, "communal water pump + trough","t"),
  ("village","mounting_block",2,2,2, "horse mounting steps",""),
  ("village","root_cellar",   5,5,4, "earth-mounded cellar + plank door (enterable)","w"),
  ("village","midden_heap",   3,3,2, "refuse / compost heap",""),
  ("village","washing_line",  6,2,3, "washing strung between posts","w"),
  ("village","herb_garden",   5,5,2, "raised herb beds + wattle edge","w"),
  ("village","allotment",     7,5,1, "tilled vegetable plot + rows","w"),
  # --- farm & rural ---
  ("farm","field_furrows", 11,11,1,"ploughed field strip","w"),
  ("farm","hay_rick",      5,5,7,  "thatch-capped haystack rick","t"),
  ("farm","scarecrow",     2,2,4,  "scarecrow on a cross-post",""),
  ("farm","cattle_byre",   9,7,6,  "timber cow shed (enterable)","tw"),
  ("farm","shepherd_hut",  5,4,5,  "wheeled shepherd's hut","w"),
  ("farm","sheep_fold",    9,9,2,  "hurdle-fenced sheep fold","w"),
  ("farm","grain_silo",    5,5,9,  "round granary silo","t"),
  ("farm","vineyard_row",  9,2,3,  "staked vine row / trellis","w"),
  ("farm","orchard_tree",  5,5,7,  "trained fruit tree + props","w"),
  ("farm","field_stile",   2,3,3,  "step-over stile in a wall",""),
  ("farm","plough",        4,2,3,  "wooden plough + harness","w"),
  # --- crafts & industry ---
  ("craft","sawpit",        6,4,3, "two-man sawpit + log","w"),
  ("craft","tannery",       8,7,4, "tanning pits + drying frames","w"),
  ("craft","loom_shed",     7,6,6, "weaver's shed + loom (enterable)","tw"),
  ("craft","charcoal_mound",5,5,4, "earthed charcoal-burner mound","w"),
  ("craft","malthouse",     9,7,7, "malting floor + kiln (enterable)","tw"),
  ("craft","glassworks",    7,6,7, "glassblower's furnace + cooling","tw"),
  ("craft","chandlery",     5,5,6, "candlemaker's vats + racks","w"),
  ("craft","apothecary",    6,6,8, "herbalist shop + drying bunches","t"),
  ("craft","smithy_yard",   8,7,6, "open forge yard + anvil + quench","tw"),
  ("craft","quarry_face",   11,7,7,"worked stone-quarry face + ramp","w"),
  ("craft","ropewalk",      13,3,4,"long rope-twisting walk","w"),
  ("craft","brick_clamp",   6,6,4, "stacked brick firing clamp","w"),
  # --- tavern & gathering ---
  ("tavern","tavern_front",  11,3,9,"timbered alehouse facade + hung sign","t"),
  ("tavern","ale_store",     5,5,4, "stacked ale casks + tap","w"),
  ("tavern","hanging_sign",  3,2,5, "wrought-bracket inn sign",""),
  ("tavern","trestle_tables",7,5,2, "outdoor trestle tables + benches","w"),
  ("tavern","spit_roast",    3,3,3, "open spit-roast over a firepit",""),
  ("tavern","maypole",       5,5,11,"ribboned maypole + green","t"),
  ("tavern","bonfire",       5,5,5, "festival bonfire stack","w"),
  # --- siege & training ---
  ("siege","trebuchet",     7,5,9,  "counterweight trebuchet","t"),
  ("siege","catapult",      5,5,5,  "torsion onager catapult","w"),
  ("siege","ballista",      5,3,4,  "bolt-throwing ballista","w"),
  ("siege","battering_ram", 9,4,5,  "roofed battering ram","w"),
  ("siege","siege_tower",   7,7,17, "wheeled assault belfry","t"),
  ("siege","mantlet",       4,2,4,  "wheeled pavise shield-wall","w"),
  ("siege","pell_post",     2,2,4,  "sword-training pell post",""),
  ("siege","archery_butts", 9,4,4,  "archery butts + targets","w"),
  ("siege","war_tent",      7,7,6,  "captain's campaign tent","tw"),
  ("siege","palisade",      9,2,6,  "sharpened timber palisade run","tw"),
  ("siege","watch_post",    3,3,9,  "raised lookout post","t"),
  # --- graveyard & memorial ---
  ("graveyard","gravestone",   2,2,3, "leaning carved headstone",""),
  ("graveyard","table_tomb",   4,3,2, "chest / table tomb","w"),
  ("graveyard","mausoleum",    7,7,9, "family tomb-house (enterable)","t"),
  ("graveyard","charnel_house",7,6,6, "bone-store charnel building","tw"),
  ("graveyard","calvary_cross",4,4,8, "raised crucifix on steps","t"),
  ("graveyard","plague_pit",   7,5,3, "covered mass grave + marker","w"),
  ("graveyard","ossuary",      5,5,5, "stacked-bone ossuary vault","w"),
  ("graveyard","sarcophagus",  4,3,3, "carved stone sarcophagus",""),
  # --- fantasy / fey ---
  ("fantasy","wizard_tower",   9,9,22, "crooked mage's tower + observatory","t"),
  ("fantasy","witch_hut",      6,6,7,  "swamp witch's stilt hut","w"),
  ("fantasy","heart_tree",     9,9,12, "great shrine-tree + offerings","tw"),
  ("fantasy","fairy_ring",     7,7,1,  "mushroom fairy ring","w"),
  ("fantasy","standing_stones",11,11,7,"rough megalith ring (original)","w"),
  ("fantasy","troll_bridge",   9,5,6,  "mossy under-bridge troll lair","w"),
  ("fantasy","monster_bones",  9,4,6,  "great-beast skeleton remains","tw"),
  ("fantasy","adventurer_camp",7,7,4,  "abandoned adventurers' camp + loot","w"),
  ("fantasy","dig_site",       9,7,4,  "archaeology dig + tools","w"),
  ("fantasy","ruined_arch",    7,3,8,  "lone surviving ruined archway","tw"),
  ("fantasy","hermit_cave",    7,6,6,  "hermit's rock cell + shrine","w"),
  # --- more fortification ---
  ("defense","city_gate",      13,4,15,"twin-tower city gate","t"),
  ("defense","city_wall",      12,4,9, "curtain city-wall run + wall-walk","tw"),
  ("defense","corner_bastion", 11,11,11,"angled corner bastion","t"),
  ("defense","postern_gate",   5,3,6,  "small hidden sally gate","t"),
]

# whole-structure plots — single size, no variants
STRUCT = [
  ("watchtower",11,11,24,"whole watchtower"),("well_full",9,9,10,"whole well"),
  ("shrine_full",13,11,15,"whole shrine/temple"),("cairn_full",9,9,13,"whole cairn"),
  ("cottage",11,9,11,"whole cottage"),("chapel",15,11,18,"whole chapel"),
  ("bridge_full",25,7,12,"whole bridge"),("keep",17,17,28,"whole keep/donjon"),
  ("monument",9,9,18,"statue monument"),("ruin_full",17,13,12,"whole ruin"),
  ("market_square",21,21,9,"market square"),("gatehouse_full",45,18,38,"whole gatehouse"),
]

def clamp(v): return max(2, int(round(v)))

# every buildable thing also gets a _ruined twin (§3.2 "broken like a person made it, then time happened"),
# EXCEPT things that are already a ruin or where decay is silly.
RUIN_SKIP = {"fairy_ring","credit_sign","midden_heap","field_furrows","allotment","rubble_pile"}
def ruinable(name):
    if name in RUIN_SKIP: return False
    return not any(k in name for k in ("ruin","broken","collapse","rubble"))
RUIN_HINT = " — RUINED: collapsed, mossy, blocks missing, overgrown"

out = []
for cat,name,w,d,h,hint,axes in BASE:
    out.append({"cat":cat,"name":name,"w":w,"d":d,"h":h,"hint":hint})
    if "s" in axes: out.append({"cat":cat,"name":name+"_short","w":w,"d":d,"h":clamp(h*0.55),"hint":hint+" — short/squat"})
    if "t" in axes: out.append({"cat":cat,"name":name+"_tall", "w":w,"d":d,"h":clamp(h*1.65),"hint":hint+" — tall"})
    if "w" in axes: out.append({"cat":cat,"name":name+"_wide", "w":clamp(w*1.7),"d":d,"h":h,"hint":hint+" — wide/long run"})
    if ruinable(name): out.append({"cat":cat,"name":name+"_ruined","w":w,"d":d,"h":h,"hint":hint+RUIN_HINT})
for name,w,d,h,hint in STRUCT:
    out.append({"cat":"structure","name":name,"w":w,"d":d,"h":h,"hint":hint})
    out.append({"cat":"structure","name":name+"_ruined","w":w,"d":d,"h":h,"hint":hint+RUIN_HINT})

p = os.path.join("config","wnl_pathways","part_catalog.json")
os.makedirs(os.path.dirname(p), exist_ok=True)
with open(p,"w",encoding="utf-8") as f: json.dump(out, f, indent=2)
json.loads(open(p,encoding="utf-8").read())  # validate
cats = {}
for e in out: cats[e["cat"]] = cats.get(e["cat"],0)+1
print(f"wrote {len(out)} parts -> {p}")
for c,n in cats.items(): print(f"  {c}: {n}")
